# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  empoweridmicroservicewebapi:
    image: empoweridmicroservicewebapi
    build:
      context: .
      dockerfile: EmpowerIdMicroservice.WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7041:7041
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
